set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]


set_property PACKAGE_PIN V17 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

set_property IOSTANDARD LVCMOS33 [get_ports {acc[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {acc[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {acc[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {acc[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {acc[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {acc[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {acc[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {acc[0]}]


set_property PACKAGE_PIN U16 [get_ports {acc[0]}]
set_property PACKAGE_PIN E19 [get_ports {acc[1]}]
set_property PACKAGE_PIN U19 [get_ports {acc[2]}]
set_property PACKAGE_PIN V19 [get_ports {acc[3]}]
set_property PACKAGE_PIN W18 [get_ports {acc[4]}]
set_property PACKAGE_PIN U15 [get_ports {acc[5]}]
set_property PACKAGE_PIN U14 [get_ports {acc[6]}]
set_property PACKAGE_PIN V14 [get_ports {acc[7]}]

set_property PACKAGE_PIN W7 [get_ports {seg_led[0]}]					
	 set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[0]}]
 set_property PACKAGE_PIN W6 [get_ports {seg_led[1]}]					
	 set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[1]}]
 set_property PACKAGE_PIN U8 [get_ports {seg_led[2]}]					
	 set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[2]}]
 set_property PACKAGE_PIN V8 [get_ports {seg_led[3]}]					
	 set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[3]}]
 set_property PACKAGE_PIN U5 [get_ports {seg_led[4]}]					
	 set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[4]}]
 set_property PACKAGE_PIN V5 [get_ports {seg_led[5]}]					
	 set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[5]}]
 set_property PACKAGE_PIN U7 [get_ports {seg_led[6]}]					
	 set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[6]}]



 set_property PACKAGE_PIN U2 [get_ports {seg_ctrl[0]}]					
	 set_property IOSTANDARD LVCMOS33 [get_ports {seg_ctrl[0]}]
 set_property PACKAGE_PIN U4 [get_ports {seg_ctrl[1]}]					
	 set_property IOSTANDARD LVCMOS33 [get_ports {seg_ctrl[1]}]
 set_property PACKAGE_PIN V4 [get_ports {seg_ctrl[2]}]					
	 set_property IOSTANDARD LVCMOS33 [get_ports {seg_ctrl[2]}]
 set_property PACKAGE_PIN W4 [get_ports {seg_ctrl[3]}]					
	 set_property IOSTANDARD LVCMOS33 [get_ports {seg_ctrl[3]}]